name: Node CI

on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v3.0.0
            
            - name: Use Node.js 16.13.1
              uses: actions/setup-node@v3.4.1
              with:
                  node-version: 16.13.1

            - name: yarn install
              run: yarn install --frozen-lockfile
              env:
                  CI: true

            - name: yarn build
              run: yarn build

            - name: yarn test:coverage
              if: github.ref == 'refs/heads/master'
              run: yarn test:coverage
              env:
                  CI: true

            - name: Upload Coverage to codecov
              if: github.ref == 'refs/heads/master'
              uses: codecov/codecov-action@v3.1.0
              with:
                  token: ${{secrets.CODECOV_TOKEN}}
                  file: ./packages/server/coverage/clover.xml

            - name: yarn test
              if: github.ref != 'refs/heads/master'
              run: yarn test
              env:
                  CI: true
